kind: pipeline
name: default

workspace:    
  base: /go
  path: src/github.com/wmwm001/go-drone-hello-world

steps:
  - name: build
   image: golang
   commands:
     - go get
     - go build -o output
     - chmod +x output
  - name: test
    image: golang
    commands:
      - go get
      - go test
  - name: run
    image: golang
    commands:
      - go get
      - go build -o output
      - chmod +x output
      - ./output
